services:
  - type: web
    name: ledgerpro-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    nodeVersion: 18.17.1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: true
    autoDeploy: true
