name: Release LedgerPro

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: rajdipk/Ledgerpro-Extended
          ref: main
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up JDK for Android build
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
        run: |
          echo $env:ENCODED_KEYSTORE | base64 -d > android/app/ledgerpro.keystore

      - name: Install dependencies
        run: |
          npm ci
          npm install -g electron-builder @ionic/cli

      - name: Get version from tag
        id: get_version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Windows Electron app
        run: |
          electron-builder --windows --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Android app
        run: |
          ionic capacitor build android --release
          cd android
          ./gradlew assembleRelease
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: LedgerPro ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/LedgerPro-Setup.exe
            android/app/build/outputs/apk/release/app-release.apk
          body: |
            # LedgerPro ${{ env.VERSION }}
            
            ## What's New
            - See CHANGELOG.md for details
            
            ## Downloads
            - Windows: LedgerPro-Setup.exe
            - Android: LedgerPro.apk
            
            ## Branches Updated
            - main
            - feature/billing-system
            - feature/inventory-management-extended
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename and Upload Android APK
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/LedgerPro.apk
